### ISSUE TITLE
Class java.util.ollectionsFactory was not found

### ISSUE THREAD

**Issue by hohwille** [m-m-m/tvm#1]
```
[ERROR] Class java.util.ollectionsFactory was not found
    at java.util.Map.of(TMap.java:227)
    at io.github.mmm.property.impl.PropertyFactoryManagerImpl.<clinit>(PropertyFactoryManagerImpl.java:30)
    at io.github.mmm.property.factory.PropertyFactoryManager.get(PropertyFactoryManager.java:171)
    at io.github.mmm.bean.AbstractBean.createProperty(AbstractBean.java:191)
```

**Comment by hohwille** [comment]
To me it seems as if `Map.of(...)` is not implemented correctly in TeaVMs `TMap` class.
My assumption is that in the implementation of `TMap.of(...)` a class named `CollectionsFactory` is used. As TeaVM compiler assumes for `java.*` classes that these are emulated by a `T*` class it simply cuts of the first character from the simple name of the class resulting in this strange `java.util.ollectionsFactory` output.
However, when I look into the latest code of `TMap` inside TeaVM, I can not find `CollectionsFactory` but only `TCollections` or `TTemplateCollections`:
https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/util/TMap.java#L174

So maybe this was fixed but is not yet released...

**Comment by hohwille** [comment]
My guess is confirmed:
https://github.com/konsoletyper/teavm/blob/160fa2b1fa334c0faa3992080272db825417f29b/classlib/src/main/java/org/teavm/classlib/java/util/TMap.java#L162

**Comment by hohwille** [comment]
See this issue:
https://github.com/konsoletyper/teavm/pull/530

**Comment by hohwille** [comment]
Fixed
