### ISSUE TITLE
Method java.lang.Math.addExact(JJ)J was not found

### ISSUE THREAD

**Issue by hohwille** [m-m-m/tvm#2]
```
[ERROR] Method java.lang.Math.addExact(JJ)J was not found
    at java.time.LocalDate.plusDays(TLocalDate.java:588)
    at java.time.LocalDateTime.plusDays(TLocalDateTime.java:472)
    at java.time.Instant.parse(TInstant.java:221)
    at java.time.Instant.parse(TInstant.java:157)
```

**Comment by hohwille** [comment]
In my PR for TeaVM I fixed this by extending `TMath`:
https://github.com/konsoletyper/teavm/pull/467

I will have to provide another PR for TeaVM that only adds this change to `TMath` to get this accepted. TeaVM project is rather monolithic and perfectionalistic. Hence, I have to go for small steps that each are fully complete and consistent rather than being blocked for years...

**Comment by hohwille** [comment]
Ah, cool. This change has already been done. I just need to update TeaVM version then. Awesome.

**Comment by hohwille** [comment]
Mhm, but I am using `0.7.0-dev-1169` what seems to be the latest available release:
https://dl.bintray.com/konsoletyper/teavm/org/teavm/teavm-core/

**Comment by hohwille** [comment]
OK, missing `floorDiv` and `floorMod` methods had been added meanwhile but `toIntExact` and `addExact` are still missing. So I will create a PR in TeaVM for that.

**Comment by hohwille** [comment]
Fixed.
